### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by sclarke81** [jsakamoto/xUnitTestProjectTemplate#1]
Would you add license information to this project? I'd like to either contribute to this project or use this as the basis of a project to provide an [xBehave] project template.

[xBehave]: http://xbehave.github.io/

**Comment by jsakamoto** [comment]
@sclarke81 Thank you for contacting me,

Well, I have no plan about licensing of this project at this time...

I think, MIT License is fit for this project.
How do you think?

**Comment by sclarke81** [comment]
No problem, thanks for getting back to me.

I think MIT would be great.

How do you feel about the future of the project? Would you be interested in expanding it to include other test project templates or do you think it would be better to keep them separate?

**Comment by jsakamoto** [comment]
I did it. (commit  e04de70fdb95e89d46bd82010d6d13b99e7d17e9)

> How do you feel about the future of the project? 

This is very interested, but it is very difficult to make decision for me.

If anything I prefer to keep them separate, because we can control our own each projects quickly, rapidly.

**Comment by sclarke81** [comment]
Thank you for that.

That's fair enough, I'm still uncertain what's best at this point too. We can always see how things evolve and reassess in the future.

**Comment by ite-jankl** [comment]
A LICENSE has been added, thank you for that. This ticket is still open however. It can be closed as implemented.

**Comment by jsakamoto** [comment]
Oh, thank you for notify me.

I'll close this ticket. :)
