### ISSUE TITLE
XUnit Template should be updated to include Microsoft.NET.Test.Sdk 17.2.0 or higher.

### ISSUE THREAD

**Issue by MarkBrainfire** [jsakamoto/xUnitTestProjectTemplate#4]
Version 17.1.0 results in the "Program does not contain a static 'Main' method suitable for an entry point" error.

C# / Visual Studio 2022

Thank you.

Here's the current result:
```
<Project Sdk="Microsoft.NET.Sdk"><Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.1.0" />
    <PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.3">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector" Version="3.1.2">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

</Project>

**Comment by jsakamoto** [comment]
@MarkBrainfire Excuse me, but your report is not for the template of this repository.
The template you mentioned is provided by the .NET SDK.

See also: https://github.com/dotnet/test-templates/blob/main/template_feed/Microsoft.DotNet.Test.ProjectTemplates.6.0/content/XUnit-CSharp/Company.TestProject1.csproj

So if you want to report something about that, please visit the following link.

https://github.com/dotnet/test-templates/issues

Thank you for being so understanding.
